### ISSUE TITLE
[Bug][Workspace list] Change workspace order after returning from Workspace detail screen

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#56]
**Test step:**
1. Login to Admin
2. Navigate to Workspaces list page
3. Click on [...] icon
4. Click on Edit button
5. Do not make any changes to the Workspace detail screen.
6. Click on back button

**Expected result:**
6. Keep workspace list order
**Actual:**
6. Change the order of recently opened workspaces

Video:
https://github.com/user-attachments/assets/54209cd8-6454-40a5-83f8-2945682e0612

**Comment by Toby-Hayward** [comment]
This is expected behavior as the order is the order of view not edited. The page for editing the workspace counts as viewing. Therefore when navigating back to workspaces page it should place it at the start of the list
