### ISSUE TITLE
[Bug][Workspace detail] Can not view Workspace detail and delete workspace

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#61]
Version: 1.5.0
**Precondition:** At least one workspace has been created.
**Test step:**
1. On screen Workspaces list page
2. Delete 1 workspace
3. Add new workspace
4. Observe the display on the screen
**Expected result:**

2. Can delete Workspace
4. Can view Workspace detail page
**Actual:**
2. Cannot delete Workspace
4. Cannot view Workspace detail page, show message "This workspace does not exits"

Video: https://github.com/user-attachments/assets/9cf33c67-914e-4e1a-bd89-fe214dfd30b9

**Comment by Toby-Hayward** [comment]
Should be fixed, backend was down for part of that day. If its not fixed move back to Todo category

**Comment by thomas-vmogroup** [comment]
22/11/2024: Can view workspace detail and delete workspace
