### ISSUE TITLE
[Bug][Block][ConvertDocumentContent] Cannot delete all text in to_format box

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#64]
Precondition: Open Workspace detail page

Test step:
1. Search block ConvertDocumentContent
2. Add block
3. Click to "Setting" icon
4. Delete all text in **to_format** box

Expected result:
4. Can delete all text
Actual:
4. Cannot delete all text

Video: https://github.com/user-attachments/assets/ea9192b9-6b73-4356-8095-5ff835628b63

**Comment by Toby-Hayward** [comment]
Is expected behavior for enums in forms. So i think  alg to leave as is
