### ISSUE TITLE
[Bug][Workspace detail] Can not upload .mp4 file with file size > 30MB

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#79]
**Step:**
1. Open workspace detail page
2. Open Files Tab
3. Click on Upload files button
4. Select file with file size = 30.5MB
5. On the Upload Files to Workspace popup, click on Upload files button

**Suggestion:** 
5. Displays a message that the file size exceeds the allowed limit --> Enduser can recognize the error and upload another file with a smaller size.

**Actual:** 
5. Displays a message that is not clear: "There was an error uploading your files."
Image: ![Image](https://github.com/user-attachments/assets/db24493c-c997-44a8-983d-2077e737077b)

**Comment by marcovem** [comment]
We currently have a limit on this, it is being worked on.

**Comment by thomas-vmogroup** [comment]
Tested on 2nd May
Should display a message that the file size exceeds the allowed limit --> End user can recognize the error and upload another file with a smaller size.
![Image](https://github.com/user-attachments/assets/e4720c8d-fd1e-4301-bacc-4da34f257273)
