### ISSUE TITLE
[Bug][Workspace detail] Cannot delete or add link of block with prompt

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#83]
**Test step:**
1. Add new workspace
2. Open workspace detail
3. Delete the Prompt and Analyzer block line links
4. Delete again then add block line again

**Expected result:**
3. Deleted successfully
4. Added successfully

**Actual:**
3. Delete unsuccessfully
4. Cannot add block line

Video:https://github.com/user-attachments/assets/134ffe8b-398a-4373-be61-1333a1d5af02

**Comment by Toby-Hayward** [comment]
i believe this has been fixed and i can recreate it. But tag me if you can get this issue to occur again

**Comment by thomas-vmogroup** [comment]
19/12/2024: Verify done
https://github.com/user-attachments/assets/3c338e11-cfdf-45cf-96e1-f6bdb7fa1587
