### ISSUE TITLE
[Bug][Sandbox][User site] Show multiple responses after user starts chatting with Model gpt-4o-2

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#84]
**Step:**
1. Add new workspace
2. Add model gpt-4o-2 for block LLMWithTools
3. Add model gpt-4o-2 for block Analyzer
4. Open Sandbox or User site
5. Start a conversation with "Hey"
6. Observe response

**Expected result:**
Show only 1 response

**Actual:**
Show 4 responses
Admin site:
![Image](https://github.com/user-attachments/assets/aead9016-9882-488c-b406-23b3136f23cc)

Sandbox:
![Image](https://github.com/user-attachments/assets/f16bc1fc-fc78-498e-bae3-97a81d52cec7)

Video: https://github.com/user-attachments/assets/9ba346b8-638a-4ac7-9d0e-19087a697de0

**Comment by Toby-Hayward** [comment]
Should be fixed. There was an issue with duplicate connections so it was outputting the response multiple times
