### ISSUE TITLE
[Bug][Workspace detail] Cannot add new file (input) when file (output) already exists

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#85]
**Precondition:** Open Workspace detail page
**Test step:**
1. Add new outputs = Files
2. Delete Files in step 1
3. Add new inputs = Files

**Expected result:**
Can delete file in step 1 and add new file input successfully

**Actual:**
Cannot add new files (input), show msg "Input with this name already exists"

Image: ![Image](https://github.com/user-attachments/assets/f3380119-445a-4917-95d9-938c504b8eb6)

**Comment by Toby-Hayward** [comment]
On pr to link for it but has been fixed
