### ISSUE TITLE
[Bug][Workspace detail] Do not display response after changing workflow

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#87]
**Test step:**
1. Create new a workspace
2. Add model for block LLMWithTools and block Analyzer is gpt-4o-2 (2024-08-06)
3. Chat with Sandbox environment --> Display response
4. Remove link between LLMWithTools and Response
5. Chat with Sandbox environment

**Expected result:**
5. Show response

**Actual:**
5. Do not display response after remove link
Video:https://github.com/user-attachments/assets/3e79796b-5d43-473c-bd96-2d77797b67a3

**Comment by Toby-Hayward** [comment]
The response is coming from llm with tools. And since the llm with tools response isn't linked to anything then you wont get a response in the UI
