### ISSUE TITLE
[Bug][Get All Document block] Wrong response message content

### ISSUE THREAD

**Issue by thomas-vmogroup** [Smartspace-ai/smartspace-sdk#88]
**Test step:**
1. Create new workspace
2. Add workspace flow with GetAllDocument Block
3. Input DataspaceID = 6aeb0fb6-ca95-4754-a1f2-c949003b5b9e and save
4. Open Sandbox, input "get all file" and wait for response

**Expected result:** Displays readable response content
**Actual:** Wrong response message content
![Image](https://github.com/user-attachments/assets/bfdec1d7-f442-4772-82f2-b5024b33feec)

**Comment by Toby-Hayward** [comment]
This is the expected output format. Its not great and will be changed with the updates over the next couple months. But atm its alg
